### ISSUE TITLE
求教 expected element name 'style' and not 'resources' 问题

### ISSUE THREAD

**Issue by Dkaishu** [supperlitt/AndroidKillerPlugin#2]
您好，我在使用ShakaApktool时遇到如下问题，请教一下此引起此问题的原因是什么，您当时是如何修复的？

I: 反编译 values */* XMLs...
java.lang.NullPointerException
	at b.a.d.a.a.x.a(Unknown Source)
	at b.a.d.a.a.x.a(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.d.a.c(Unknown Source)
	at b.a.a.b(Unknown Source)
	at b.a.B.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at com.rover12421.shaka.cli.Main.main(Unknown Source)
java.lang.NullPointerException
	at b.a.d.a.a.x.a(Unknown Source)
	at b.a.d.a.a.x.a(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.d.a.c(Unknown Source)
	at b.a.a.b(Unknown Source)
	at b.a.B.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at com.rover12421.shaka.cli.Main.main(Unknown Source)
java.lang.NullPointerException
	at b.a.d.a.a.x.a(Unknown Source)
	at b.a.d.a.a.x.a(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.d.a.c(Unknown Source)
	at b.a.a.b(Unknown Source)
	at b.a.B.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at com.rover12421.shaka.cli.Main.main(Unknown Source)
Exception in thread "main" java.lang.IllegalArgumentException: expected element name 'style' and not 'resources'
	at org.e.a.a.c(Unknown Source)
	at b.a.d.a.a(Unknown Source)
	at b.a.d.a.c(Unknown Source)
	at b.a.a.b(Unknown Source)
	at b.a.B.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at b.b.a.a(Unknown Source)
	at com.rover12421.shaka.cli.Main.main(Unknown Source)

**Comment by supperlitt** [comment]
其实主要的功能，就是在apktool进行执行命令的时候，使用 -r 不处理资源。这样大部分都可以直接过了。

**Comment by matthuo333** [comment]
> 其实主要的功能，就是在apktool进行执行命令的时候，使用 -r 不处理资源。这样大部分都可以直接过了。

具体怎么解？

**Comment by Dkaishu** [comment]
> > 其实主要的功能，就是在apktool进行执行命令的时候，使用 -r 不处理资源。这样大部分都可以直接过了。
> 
> 具体怎么解？

**Comment by Dkaishu** [comment]
直接使用 apktool，带 -r 参数
